name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/nonebot-plugin-lxns-maimai
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@master

    - name: Setup Python environment
      uses: ./.github/actions/setup-python

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
